---
abstract: 'Interact with a remote Pinto repository'
author:
  - 'Jeffrey Ryan Thalhammer <jeff@imaginative-software.com>'
build_requires:
  File::Find: 0
  HTTP::Body: 0
  HTTP::Response: 0
  IO::String: 0
  Module::Build: 0.3601
  Test::Mock::LWP::Dispatch: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pinto-Remote
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Pinto::Remote:
    file: lib/Pinto/Remote.pm
    version: 0.047
  Pinto::Remote::Action:
    file: lib/Pinto/Remote/Action.pm
    version: 0.047
  Pinto::Remote::Action::Add:
    file: lib/Pinto/Remote/Action/Add.pm
    version: 0.047
  Pinto::Remote::Action::Install:
    file: lib/Pinto/Remote/Action/Install.pm
    version: 0.047
  Pinto::Remote::Config:
    file: lib/Pinto/Remote/Config.pm
    version: 0.047
  Pinto::Remote::Logger:
    file: lib/Pinto/Remote/Logger.pm
    version: 0.047
  Pinto::Remote::Result:
    file: lib/Pinto/Remote/Result.pm
    version: 0.047
requires:
  Carp: 0
  File::Temp: 0
  File::Which: 0
  HTTP::Request::Common: 0
  JSON: 0
  LWP::UserAgent: 0
  Log::Dispatch: 0
  Moose: 0
  MooseX::Types::Moose: 0
  Pinto::Constants: 0
  Pinto::Exception: 0
  Pinto::Types: 0
  URI: 0
  namespace::autoclean: 0
  perl: 5.006
resources:
  bugtracker: https://github.com/thaljef/Pinto-Remote/issues
  repository: git://github.com/thaljef/Pinto-Remote.git
version: 0.047
