---
abstract: 'Interact with a remote Pinto repository'
author:
  - 'Jeffrey Ryan Thalhammer <jeff@imaginative-software.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pinto-Remote
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  App::Pinto::Remote:
    file: lib/App/Pinto/Remote.pm
    version: 0.033
  App::Pinto::Remote::Command:
    file: lib/App/Pinto/Remote/Command.pm
    version: 0.033
  App::Pinto::Remote::Command::add:
    file: lib/App/Pinto/Remote/Command/add.pm
    version: 0.033
  App::Pinto::Remote::Command::list:
    file: lib/App/Pinto/Remote/Command/list.pm
    version: 0.033
  App::Pinto::Remote::Command::manual:
    file: lib/App/Pinto/Remote/Command/manual.pm
    version: 0.033
  App::Pinto::Remote::Command::pin:
    file: lib/App/Pinto/Remote/Command/pin.pm
    version: 0.033
  App::Pinto::Remote::Command::ping:
    file: lib/App/Pinto/Remote/Command/ping.pm
    version: 0.033
  App::Pinto::Remote::Command::remove:
    file: lib/App/Pinto/Remote/Command/remove.pm
    version: 0.033
  App::Pinto::Remote::Command::statistics:
    file: lib/App/Pinto/Remote/Command/statistics.pm
    version: 0.033
  App::Pinto::Remote::Command::unpin:
    file: lib/App/Pinto/Remote/Command/unpin.pm
    version: 0.033
  App::Pinto::Remote::Command::version:
    file: lib/App/Pinto/Remote/Command/version.pm
    version: 0.033
  Pinto::Remote:
    file: lib/Pinto/Remote.pm
    version: 0.033
  Pinto::Remote::Action:
    file: lib/Pinto/Remote/Action.pm
    version: 0.033
  Pinto::Remote::Action::Add:
    file: lib/Pinto/Remote/Action/Add.pm
    version: 0.033
  Pinto::Remote::Action::List:
    file: lib/Pinto/Remote/Action/List.pm
    version: 0.033
  Pinto::Remote::Action::Nop:
    file: lib/Pinto/Remote/Action/Nop.pm
    version: 0.033
  Pinto::Remote::Action::Pin:
    file: lib/Pinto/Remote/Action/Pin.pm
    version: 0.033
  Pinto::Remote::Action::Remove:
    file: lib/Pinto/Remote/Action/Remove.pm
    version: 0.033
  Pinto::Remote::Action::Statistics:
    file: lib/Pinto/Remote/Action/Statistics.pm
    version: 0.033
  Pinto::Remote::Action::Unpin:
    file: lib/Pinto/Remote/Action/Unpin.pm
    version: 0.033
  Pinto::Remote::Batch:
    file: lib/Pinto/Remote/Batch.pm
    version: 0.033
  Pinto::Remote::Config:
    file: lib/Pinto/Remote/Config.pm
    version: 0.033
  Pinto::Remote::Result:
    file: lib/Pinto/Remote/Result.pm
    version: 0.033
requires:
  App::Cmd::Setup: 0
  Carp: 0
  Class::Load: 0
  LWP::UserAgent: 0
  Moose: 0
  MooseX::Types::Moose: 0
  Pinto::Interface::Authorable: 0
  Pinto::Types: 0
  Pod::Usage: 0
  base: 0
  namespace::autoclean: 0
  overload: 0
  perl: 5.006
  strict: 0
  version: 0
  warnings: 0
resources:
  bugtracker: https://github.com/thaljef/Pinto-Remote/issues
  repository: git://github.com/thaljef/Pinto-Remote.git
version: 0.033
